# Generated by Django 4.2.6 on 2024-02-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=250)),
                ('exercise_thumnail', models.ImageField(upload_to='fit/files/thumnails')),
                ('exercise_body_part', models.CharField(max_length=100)),
                ('exercise_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_and_reps', models.IntegerField(max_length=500)),
                ('weigth', models.IntegerField(max_length=1000)),
                ('comment', models.TextField()),
            ],
        ),
    ]
