# Generated by Django 4.2.6 on 2024-02-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='set_and_reps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='weigth',
            field=models.IntegerField(),
        ),
    ]
