# Generated by Django 4.2.6 on 2024-02-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0003_rename_weigth_note_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biceps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=250)),
                ('exercise_thumnail', models.ImageField(upload_to='fit/files/thumnails/Biceps')),
                ('exercise_body_part', models.CharField(max_length=100)),
                ('exercise_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=250)),
                ('exercise_thumnail', models.ImageField(upload_to='fit/files/thumnails/Chest')),
                ('exercise_body_part', models.CharField(max_length=100)),
                ('exercise_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shoulders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=250)),
                ('exercise_thumnail', models.ImageField(upload_to='fit/files/thumnails/Shoulders')),
                ('exercise_body_part', models.CharField(max_length=100)),
                ('exercise_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='abs',
            name='exercise_thumnail',
            field=models.ImageField(upload_to='fit/files/thumnails/Abs'),
        ),
    ]
